services:

    dashboard:
        extends:
            file: common-services.yml
            service: dashboard
        container_name: frontend-dashboard
        ports:
            - "3000:3000"
        environment:
            - HOSTNAME=0.0.0.0
            - PORT=3000
        networks:
            - mym-network

    landing:
        extends:
            file: common-services.yml
            service: landing
        container_name: frontend-landing
        ports:
            - "3001:3001"
        environment:
            - HOSTNAME=0.0.0.0
            - PORT=3001
        networks:
            - mym-network

networks:
    mym-network:
        external: true
