services:

    dashboard:
        container_name: frontend-dashboard
        build:
            context: .
            dockerfile: ./apps/dashboard/.docker/Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "3000:3000"
        networks:
            - mym-network

    landing:
        container_name: frontend-landing
        build:
            context: .
            dockerfile: ./apps/landing/.docker/Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "3001:3001"
        networks:
            - mym-network

networks:
    mym-network:
        external: true
